### ISSUE TITLE
 lambdasinaction code example Eorror In Chap3

### ISSUE THREAD

**Issue by 156235yuan** [java8/Java8InAction#22]
I downloaded the lambdasinaction code example, but there are some errors.
For example：
The method flatMapping((<no type> dish) -> {}, toSet()) is undefined for the type Grouping in chap3 package, The code: ` private static Map<Dish.Type, Set<String>> groupDishTagsByType() {
        return menu.stream().collect(groupingBy(Dish::getType, flatMapping(dish -> dishTags.get( dish.getName() ).stream(), toSet())));
    }` 

And The method filtering((<no type> dish) -> {}, toList()) is undefined for the type Grouping in chap3 package, The code `private static Map<Dish.Type, List<Dish>> groupCaloricDishesByType() {
        return menu.stream().collect(groupingBy(Dish::getType, filtering(dish -> dish.getCalories() > 500, toList())));
    }
`

When I practice， encountered a lot of errors  .  The method toList() 、groupingBy、comparing()....is undefined for the type TestStream. 
By the way, i used jdk 1.8.0.171，Is it because the JDK version is too low ？

**Comment by bsbravo** [comment]
This is because the source code was updated to Java 9.

takeWhile is a new method added to Stream interface in Java 9:

https://docs.oracle.com/javase/9/docs/api/java/util/stream/Stream.html#takeWhile-java.util.function.Predicate-

filtering and flatMapping where added to the Collectors interface:

https://docs.oracle.com/javase/9/docs/api/java/util/stream/Collectors.html#flatMapping-java.util.function.Function-java.util.stream.Collector-

https://docs.oracle.com/javase/9/docs/api/java/util/stream/Collectors.html#filtering-java.util.function.Predicate-java.util.stream.Collector-


So, update to JDK 9.

**Comment by 156235yuan** [comment]
-

**Comment by 156235yuan** [comment]
thank you,I see in pom.xml that the environment needs jdk9. but this book is jdk8Inaction. 
Well, i admit i  was careless...
by the way, i download jdk9. its no many jar,eg:rt.jar,resource.jar... 
so, i cannot use jdk9
